workflows:
  my-workflow:
    name: Test1WorkFlow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    scripts:
        - name: Build for iOS
          script: flutter build ios
    artifacts:
      - build/**/outputs/**/*.aab