# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  source 'https://github.com/CocoaPods/Specs.git'
	platform:ios, '10.0'
	pod 'SWXMLHash', '~> 4.7.5'
	pod 'CryptoSwift'
	pod 'Alamofire', '~> 4.8.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'RealmSwift'
  
  post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end